### ISSUE TITLE
Broken Herochat integration - 2.8.7Beta

### ISSUE THREAD

**Issue by saladfingers** [MassiveCraft/Factions#1043]
Herochat integration appears to be broken in 2.8.7Beta - Faction & Allie chat can be seen by the whole server. I do not have this issue with 2.8.6.

**Comment by ulumulu1510** [comment]
We haven't changed anything in regards to the HeroChat integration in a long time.

Maybe something in HeroChat has changed, whichd be unpleasent if so.

But first, please state your version of:
* Factions
* MassiveCore
* HeroChat 
* Spigot version and build day

**Comment by saladfingers** [comment]
Factions: 2.8.7Beta
MassiveCore: 2.8.7Beta
HeroChat: 5.6.7 (modified with 'SpecialSource' from spigot)
Spigot: git-Spigot-bc01c3a-0cd6711 (built 06/03)

Also, the factions_name variable is displayed instead of the value.

[https://drive.google.com/file/d/0B-IR31WXsu8cOG5iV2VqdTFGZkU/view?usp=sharing](url)

**Comment by magnusulf** [comment]
Show your factions and massivecore mconf.

**Comment by saladfingers** [comment]
factions_mconf: http://pastebin.com/BnSQ6kqy
massivecore_mconf: http://pastebin.com/YQW1GyRf

**Comment by MarkehMe** [comment]
When you type the plugins command (```/pl```) does HeroChat show up red?

**Comment by saladfingers** [comment]
No, HeroChat is working fine in every other way,

**Comment by oloflarsson** [comment]
What version of HeroChat are you using?

**Comment by Uranusak** [comment]
Same problem, upgrade spigot1.8.9 -> 1.9
Herochat 5.6.7 -> 5.7.0
Factions  2.8.5 -> 2.8.7Beta
MassiveCore 2.8.7Beta

massivecore_mconf
`"usingRecipientChatEvent": false,`

factions_mconf
```
"chatSetFormat": false,
"chatParseTags": true,
```

Herochat/config.yml
```
format:
  default: '{color}[{nick}] &f{factions_roleprefix}&9{factions_name|rp}{prefix}{sender}&f:
```

**Comment by magnusulf** [comment]
You should use the reipientChatEvent for the faction formatting to work.

**Comment by saladfingers** [comment]
HeroChat 5.7.0 seems to break faction chat in both 2.8.6 and 2.8.7. 
HeroChat 5.6.9 only breaks faction chat in 2.8.7

**Comment by tara81** [comment]
can confirm
http://pastebin.com/m1msRth0

**Comment by tara81** [comment]
I really wish we could turn off the integration til this is fixed, I am left either not using herochat or factions at this time, due to the sheer amount of error spam.

**Comment by ulumulu1510** [comment]
Ok, as far as I can see our integration is using HeroChat 5.6.7. The problem with HeroChat 5.7 is that they have changed their API drastically and haven't given any notice on that what so ever (reffering to the bukkit page). I am VERY surprised that anything works since my IDE just light up like a christmas tree with HeroChat 5.7.

So what can you do? 5.6.7 is supposed to work fine, since we use that to compile against. If that is not working on 1.9, I can't do much. I don't know HeroChat well and we haven't used it in ages. I will see what I can do, but can't promis anything.

**Comment by saladfingers** [comment]
Are there any major differences between factions 2.8.6 and 2.8.7? I'm currently running two 1.9 servers with factions 2.8.6 and haven't noticed a problem. 

I have no issues staying on 2.8.6 just to keep Herochat working, unless there is something in 1.9 that is not protected by 2.8.6

**Comment by ulumulu1510** [comment]
@saladfingers  Probably no major changes for players/admin to be seen, but internally... a whole new world.

**Comment by ulumulu1510** [comment]
Alright ladies and gentleman, I think I managed to somewhat understand how the new system and its API works. My IDE shows no errors, but let's see whether this actually works. I will proceed to test whether it works as supposed now.

**Comment by tara81** [comment]
if u cannot fix it , can u just add a config option for turning off herochat integration because the spam is unbearable.

**Comment by tara81** [comment]
is this fixed in  2.8.8 ??

**Comment by stapleshotz** [comment]
This is still an issue for me in mcore v2.8.14 and herochat v5.6.7-snapshot and craftbukkit git-Bukkit-b103841. 

I spoke with the Herochat dev, Kainzo, on the [Spigot page](https://www.spigotmc.org/threads/herochat.127195/page-3) and they said the Herochat API hasn't changed in around 5 years? I know next to nothing about plugin development, but I think there might be some miscommunication going on here.
